[workspace]
resolver = "2"
members = ["crates/zombie-bite", "crates/zombie-bite-core"]

[workspace.package]
version = "0.5.0"
edition = "2021"
# zombienet-sdk 0.5 needs 1.90
rust-version = "1.90"
license = "Apache-2.0"
repository = "https://github.com/pepoviola/zombie-bite"
keywords = ["polkadot", "substrate", "zombienet", "fork", "testing"]

# local patch
#[patch.crates-io]
#zombienet-orchestrator =  { path = "../zombienet-sdk/crates/orchestrator" }
#zombienet-provider =  { path = "../zombienet-sdk/crates/provider" }
#zombienet-configuration = { path = "../zombienet-sdk/crates/configuration" }
#zombienet-support = { path = "../zombienet-sdk/crates/support" }
#zombienet-sdk = { path = "../zombienet-sdk/crates/sdk" }
